server:
  port: 8081

spring:
  cloud:
    stream:
      bindings:
      #因为此程序经过了两到转换，才到了接受者手中，所以发送消息的2个保持 destination一致。sample-source 的output
     # 然后到了 SampleTRansformer的 input,接受者，然后，再发送消息output到 sample-source的sink，对象，
        sample-source: 
          destination: testtock
        input:
          destination: testtock
        output:
          destination: xformed
        sample-sink:
          destination: xformed
        
          
       
          
   